###
POST http://localhost:3000/api/waypoints/allByPathByDifficultyLevel HTTP/1.1
content-type: application/json

{
    "startWaypoint": "660f352d4dfba8b6710a9bd1",
    "endWaypoint": "660f34e34dfba8b6710a9bc9",
    "level1": true,
    "level2": true,
    "level3": true
}